# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
