# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiple',
            old_name='answers',
            new_name='answer',
        ),
    ]
